{% set name = "pennies" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../src

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - multipledispatch
    - numpy
    - pandas
    - pip
    - pip
    - python
    - scipy
  run:
    - multipledispatch
    - numpy
    - pandas
    - python
    - scipy

test:
  imports:
    - pennies
    - pennies.calculators
    - pennies.market
    - pennies.models
    - pennies.reporting
    - pennies.trading

about:
  home: https://github.com/caseyclements/pennies
  license: BSD
  license_family: BSD
  license_file: 
  summary: pythonic quantitative finance library
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
